### ISSUE TITLE
Versions of grpc and fsevents are not compatible with Node 12

### ISSUE THREAD

**Issue by esturcke** [ReactTraining/hooks-workshop#14]
Using Node v12.8.0 I am seeing problems building `grpc` pulled in from `firebase` and `fsevents` pulled in from  `chokidar`:

<details>
  <summary>Logs</summary>

```
...
make: make: *** [Release/obj.target/fse/fsevents.o] Error 1*** [Release/obj.target/fse/fsevents.o] Error 1

gypgyp  ERR!ERR!  build errorbuild error

gypgyp  ERR!ERR!  stackstack Error: `make` failed with exit code: 2
 Error: `make` failed with exit code: 2
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gypgyp  ERR!ERR!  stackstack     at ChildProcess.emit (events.js:203:13)
     at ChildProcess.emit (events.js:203:13)
gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gypgyp  ERR!ERR!  SystemSystem Darwin 18.7.0
 Darwin 18.7.0
gypgyp  ERR!ERR!  commandcommand "/usr/local/Cellar/node/12.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
 "/usr/local/Cellar/node/12.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napgypi"
 ERR! cwdgyp /Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents
 ERR!gyp  cwdERR! /Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents
 node -vgyp v12.8.0
 ERR!gyp  node -v v12.8.0
ERR! node-gyp -vgyp v5.0.3
 ERR!gyp node-gyp -v  v5.0.3
ERR! not okgyp
 ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.8.0/bin/node" "/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v12.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/12.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/esturcke/work/hooks-workshop/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
...
make: *** [Release/obj.target/grpc_node/ext/channel.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/esturcke/work/hooks-workshop/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/esturcke/work/hooks-workshop/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/esturcke/work/hooks-workshop/node_modules/grpc
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/esturcke/work/hooks-workshop/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/esturcke/work/hooks-workshop/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/esturcke/work/hooks-workshop/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.8.0/bin/node" "/Users/esturcke/work/hooks-workshop/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/esturcke/work/hooks-workshop/node_modules/grpc
node-pre-gyp ERR! node -v v12.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/12.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/esturcke/work/hooks-workshop/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/esturcke/work/hooks-workshop/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
...
```
</details>

It looks like `fsevents@1.2.7` is optional for `chokadir`, but removing and regenerating the `package-lock.json` fixes that issue.

The `firebase` issue [looks like it requires a major upgrade](https://github.com/firebase/firebase-js-sdk/issues/1738) to 6.0.2-0. Updating it to 6.2.2 in `package.json` worked for me. The [breaking change](https://firebase.google.com/support/release-notes/js#version_600_-_may_7_2019) is that it no longer comes bundled with polyfills.

After both of these steps `npm i` installs fine and I was able to run the full application and register a user.

I'm not sure what browsers you need to target, but would it be possible to update these dependencies? I can put together a PR if you would like to see my changes.

**Comment by esturcke** [comment]
Specifically, I got it to run with v12 on MacOS with:

```
rm -fr node_modules
rm package-lock.json
npm add firebase@6.6.2
npm install
```

The other option that people used was the use `nvm` to use v10.

**Comment by esturcke** [comment]
Looks like node v12 is LTS now, so people might run into this more in the upcoming Hooks tour 😃

**Comment by cassidoo** [comment]
Thanks for filing this, @esturcke! We're looking into it now and put a blurb in the README in the meanwhile!

**Comment by mjackson** [comment]
Thanks, @esturcke. These steps get the install to work correctly, but I think we still need to change some of our app code to use the new firebase version. Looking into this now.

**Comment by esturcke** [comment]
Cool, yeah, I guess there's more to it. I was able to get through the workshop with `firebase@6.6.2`. 7 seemed to have more breaking changes.

**Comment by mjackson** [comment]
Weird. I just tried it again and everything worked. I must've had some old stuff hanging around still on my hard drive. Thanks for the tips, @esturcke!

**Comment by anthonybrown** [comment]
I'm having a problem building the hooks workshop repo
